item = Item.create(name: "pen", price: 2, supplier_id: 1)
item = Item.create(name: "pencil", price: 1, supplier_id: 1)
item = Item.create(name: "eraser", price: 3, supplier_id: 1)
item = Item.create(name: "note book", price: 5, supplier_id: 1)
item = Item.create(name: "ruler", price: 4, supplier_id: 1)
